ZapLog:
  ErrLog: log/err.log
  WarnLog: log/warn.log
  InfoLog: log/info.log
  Maxsize: 100
  MaxAge: 15
  MaxBackup: 30
  Compress: true
  Json: true

proxy:
  http:
    read_timeout: 10
    write_timeout: 10
    max_header_bytes: 20


Redis:
  Host: 
    - localhost:7000
    - localhost:7001
    - localhost:7002
    - localhost:7003
    - localhost:7004
    - localhost:7005
  Passwd: "1234567890"
  PoolSize: 10 
  PoolTimeout: 3